# Generated by Django 6.0.7 on 2026-08-29 20:20

from decimal import Decimal

from django.db import migrations, models


PLANS = (
    {
        "code": "Free",
        "name": "Free",
        "description": "Для тех, кто начинает изучать Telegram-аналитику",
        "monthly_price": Decimal("0.00"),
        "is_highlighted": False,
        "ordering": 1,
        "channels_limit": 3,
        "ai_requests_limit": 5,
        "features": [
            "Базовая статистика",
            "5 AI-разборов / мес",
            "Каталог каналов",
        ],
    },
    {
        "code": "Pro",
        "name": "Pro",
        "description": "Для авторов и рекламодателей, которым важны данные",
        "monthly_price": Decimal("990.00"),
        "is_highlighted": True,
        "ordering": 2,
        "channels_limit": 100,
        "ai_requests_limit": 1000,
        "features": [
            "Всё из Free",
            "Безлимит AI-разборов",
            "Контент-план на неделю",
            "Сравнение до 5 каналов",
            "Экспорт отчётов",
        ],
    },
    {
        "code": "Agency",
        "name": "Agency",
        "description": "Для агентств и команд, работающих с множеством каналов",
        "monthly_price": Decimal("4900.00"),
        "is_highlighted": False,
        "ordering": 3,
        "channels_limit": 500,
        "ai_requests_limit": 5000,
        "features": [
            "Всё из Pro",
            "До 500 каналов и групп",
            "API-доступ",
            "Командный доступ",
        ],
    },
)


def calculate_annual_price(monthly_price: Decimal) -> Decimal:
    return (monthly_price * 12 * Decimal("0.8")).quantize(Decimal("0.01"))


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")

    for plan_data in PLANS:
        monthly_price = plan_data["monthly_price"]

        Plan.objects.update_or_create(
            code=plan_data["code"],
            defaults={
                **plan_data,
                "annual_price": calculate_annual_price(monthly_price),
                "currency": "RUB",
            },
        )


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")

    Plan.objects.filter(code__in=[plan["code"] for plan in PLANS]).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("Free", "Бесплатный"),
                            ("Pro", "Продвинутый"),
                            ("Agency", "Агентский"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100),
                ),
                (
                    "description",
                    models.TextField(),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB",
                        max_length=3,
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(default=False),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "channels_limit",
                    models.PositiveIntegerField(),
                ),
                (
                    "ai_requests_limit",
                    models.PositiveIntegerField(),
                ),
                (
                    "features",
                    models.JSONField(default=list),
                ),
            ],
            options={
                "verbose_name": "тариф",
                "verbose_name_plural": "тарифы",
                "ordering": ("ordering", "id"),
            },
        ),
        migrations.RunPython(
            seed_plans,
            remove_plans,
        ),
    ]
