# Generated by Django 6.0.1 on 2026-05-15 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField(verbose_name='Текст инсайта')),
                ('insight_type', models.CharField(choices=[('trend', 'Тренд'), ('recommendation', 'Рекомендация'), ('warning', 'Предупреждение'), ('positive', 'Позитивный')], max_length=50, verbose_name='Тип инсайта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='parser.telegramchannel', verbose_name='Канал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'AI инсайт',
                'verbose_name_plural': 'AI инсайты',
                'ordering': ['-created_at'],
            },
        ),
    ]
