# Generated by Django 6.0.6 on 2026-08-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0003_post_postreaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAIBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(verbose_name="Краткое резюме (Summary)"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        max_length=50, verbose_name="Тон/Sentiment"
                    ),
                ),
                (
                    "key_topics",
                    models.JSONField(
                        default=list,
                        help_text="Список тем в формате ['тема1', 'тема2']",
                        verbose_name="Ключевые темы (JSON)",
                    ),
                ),
                (
                    "audience_insight",
                    models.TextField(verbose_name="Инсайт аудитории"),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=dict, verbose_name="Рекомендации (JSON)"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата генерации"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Версия модели AI",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_breakdown",
                        to="parser.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI разбор поста",
                "verbose_name_plural": "AI разборы постов",
            },
        ),
    ]
