# Generated by Django 6.0.7 on 2026-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0005_postanalysis_delete_postaibreakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchannel",
            name="is_verified",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Прошел верификацию"
            ),
        ),
        migrations.AddField(
            model_name="telegramchannel",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата верификации"
            ),
        ),
    ]
