# Generated by Django 6.0.7 on 2026-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0008_post_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchannel",
            name="citation_index",
            field=models.FloatField(
                db_index=True, default=0.0, verbose_name="Индекс цитируемости"
            ),
        ),
    ]
