# Generated by Django 6.0.1 on 2026-03-09 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image_url',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='обложка группы'),
        ),
    ]
