# Generated by Django 6.0.7 on 2026-09-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_channels", "0003_savedcollection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curated_groups",
                related_query_name="curated_group",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Куратор",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="saves_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество сохранений"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
