# Generated by Django 6.0.7 on 2026-08-11 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("parser", "0003_post_postreaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_identifier",
                    models.CharField(
                        max_length=255,
                        verbose_name="Идентификатор канала (username или url)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=255, verbose_name="Категория запроса"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=255,
                        verbose_name="Страна, к которой относится запрос",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        max_length=255,
                        verbose_name="Язык, к которому относится запрос",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("duplicate", "Дубликат"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=255,
                        verbose_name="Статус запроса",
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Причина отклонения запроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время создания запроса",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время обработки запроса",
                    ),
                ),
                (
                    "channel_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_requests",
                        to="parser.telegramchannel",
                        verbose_name="Канал, к которому относится запрос",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор, обработавший запрос",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, отправивший запрос",
                    ),
                ),
            ],
        ),
    ]
