# Generated by Django 5.2.4 on 2025-10-08 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
    ]
