# Generated by Django 6.0.7 on 2026-09-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_role_alter_user_role_userrolehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_reports",
                    models.BooleanField(
                        default=True, verbose_name="Еженедельные отчёты"
                    ),
                ),
                (
                    "trend_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления о трендах"
                    ),
                ),
                (
                    "new_features",
                    models.BooleanField(
                        default=True, verbose_name="Новости о новых функциях"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
    ]
